  # my global config
  global:
    scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    # scrape_timeout is set to the global default (10s).

  # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
  rule_files:
   - "rules/recording_rules.yml"

  scrape_configs:
    - job_name: 'prometheus'

      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

      static_configs:
        - targets: ['localhost:9090']

    - job_name: 'auth-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['auth-service:8082']
        
    - job_name: 'account-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['account-service:8083']
        
    - job_name: 'job-offer-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['job-offer-service:8084']
        
    - job_name: 'logging-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['logging-service:8085']
        
    - job_name: 'messaging-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['messaging-service:8086']
        
    - job_name: 'notification-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['notification-service:8094']
        
    - job_name: 'post-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['post-service:8087']

    - job_name: 'node_exporter'
      static_configs:
        - targets: [ 'node-exporter:9100' ]

    - job_name: 'grafana'
      static_configs:
        - targets: ['grafana:3000']

    - job_name: 'cAdvisor'
      static_configs:
        - targets: [ 'cadvisor:8080' ]
